name: CI

on:
	push:
		branches: [ "**" ]
	pull_request:
		branches: [ "**" ]

jobs:
	phpcompat:
		runs-on: ubuntu-latest
		strategy:
			matrix:
				php-versions: ['8.0', '8.2', '8.3']

		steps:
			- uses: actions/checkout@v4

			- name: Setup PHP
				uses: shivammathur/setup-php@v2
				with:
					php-version: ${{ matrix.php-versions }}
					tools: composer:v2

			- name: Install Composer dependencies
				run: composer install --prefer-dist --no-progress

			- name: Audit dependencies for known vulnerabilities
				run: composer audit --no-dev

			- name: Run PHPCS
				run: composer run phpcs

			- name: Run PHPUnit
				run: composer run phpunit
